export const ClientData=[
    {
    clientImage:'./clients/Microsoft.svg'
    },
    {
    clientImage:'./clients/Google.svg'
    },
    {
    clientImage:'./clients/Dropbox.svg'
    },
    {
    clientImage:'./clients/Netflix.svg'
    },
    {
    clientImage:'./clients/Shopify.svg'
    },
    {
    clientImage:'./clients/Slack.svg'
    },
    {
    clientImage:'./clients/Spotify.svg'
    },
    {
    clientImage:'./clients/Tinder.svg'
    },
    {
    clientImage:'./clients/YouTube.svg'
    },
    {
    clientImage:'./clients/Zoom.svg'
    },
    {
    clientImage:'./clients/Amazon.svg'
    },
    {
    clientImage:'./clients/Instagram.svg'
    }
];